import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Heading from "./component/heading";
import { ThemeProvider } from "@/components/theme-provider";

const test = Inter({ subsets: ["latin"] });
const inter = Roboto({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "TravelFun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Heading />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
